service:
  type: LoadBalancer
  port: 3000
persistence:
  enabled: true
  type: pvc
  size: 1Gi
podAnnotations:
  kubelibrary: testing
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"