apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa
  labels: 
    source: mysa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysa-admin-binding
subjects:
- kind: ServiceAccount
  name: mysa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: mysa-token
  annotations:
    kubernetes.io/service-account.name: mysa
type: kubernetes.io/service-account-token
